### ISSUE TITLE
Running Sbt to compile hangs at downloading

### ISSUE THREAD

**Issue by DaveGit** [djspiewak/anti-xml#14]
Hi Daniel,
I have downloaded the latest version of anti-xml and try to compile with sbt but it hangs. I had the same with a previous version.
`C:\Users\Dave\.ivy2\cache\org.scala-lang\scala-compiler\jars\scala-compiler-2.9.0.jar.part`
stops/ hangs at 960 kB
System: Windows 7 Home Premium

I  am also wondering  why downloading if it is possible to copy directly from `C:\scala-2.8.1.final\lib` or `C:\scala-2.9.0.final\lib` directory since I have the scala 2.8.1.final and 2.9.0.final distributions locally?
Maybe searchpath variable in project properties file?

Greetings,
Dave
# Output

```
C:\scala-2.9.0.final\djspiewak-anti-xml-2e196e7>java -Xmx512M -jar "c:\sbt\sbt-l
aunch-0.7.5.jar"
Getting Scala 2.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
        confs: [default]
        2 artifacts copied, 0 already retrieved (9911kB/374ms)
Getting org.scala-tools.sbt sbt_2.7.7 0.7.5 ...
:: retrieving :: org.scala-tools.sbt#boot-app
        confs: [default]
        16 artifacts copied, 0 already retrieved (4271kB/951ms)
[info] Recompiling plugin definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info]
[info] Updating plugins...
[info] :: retrieving :: plugin-definition#plugin-definition_2.7.7 [sync]
[info]  confs: [compile, runtime, test, provided, system, optional, sources, jav
adoc]
[info]  3 artifacts copied, 0 already retrieved (174kB/187ms)
[success] Plugins updated successfully.
[info]
[info]  Extracted source plugin .\lib_managed\scala_2.7.7\sbt-eclipsify-0.7.0.ja
r ...
[info]  Extracted source plugin .\lib_managed\scala_2.7.7\sbt-scct-for-2.8-0.1-S
NAPSHOT.jar ...
[info] Recompiling plugin...
[info]    Source analysis: 8 new/modified, 0 indirectly invalidated, 0 removed.
[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
Getting Scala 2.9.0 ...
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.9.0/sc
ala-compiler-2.9.0.jar ...
```

**Comment by djspiewak** [comment]
That seems unusual.  If you kill SBT and then try again, does it still have issues?  This seems like it is likely an issue with your internet connection, since SBT is just delegating to Ivy2, which is extremely well-tested and reliable for these sorts of things.  There is probably a way to convince Ivy2 to use the version of Scala you have installed locally, but I honestly don't think it's worth it.  That would almost certainly be more effort than getting the download to work, and less certain of success.

**Comment by DaveGit** [comment]
Probably it was due to the jre 1.7 build 140 EA compatibility with sbt/ivy2. I uninstalled it and everything downloaded fast without problems running with the jre1.6 of the jdk1.6. I could compile after setting specs2 to 1.3. Crossbuilding with +release also worked. Thanks. I close this issue.
