### ISSUE TITLE
Implement Identifier Checking (for reserved characters)

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/anti-xml#16]
Currently, it is possible to do something like this following:

``` scala
Elem(None, "<", Attributes(), Group())
```

Clearly, this `Elem` name doesn't make any sense.  We should run all identifiers through a regexp to ensure this case is rejected at runtime.

**Comment by jespersm** [comment]
An exception should be thrown in Elem#apply, right?
Normally, I'd go for IlleglArgumentException or similar, is this bad Scala style?

**Comment by djspiewak** [comment]
Actually, it should be thrown in the constructor for `Elem`.  It's easier (and more efficient at runtime) if we stick with the compiler auto-generated `apply` method on the `Elem` companion object.

`IllegalArgumentException` is actually just right for the situation.  I'm usually a bit lazy with my exceptions in Scala and I just use `RuntimeException` everywhere (which is _definitely_ bad Scala style).  :-)  That reminds me: I really should go through and replace those instances in Anti-XML…
