### ISSUE TITLE
Support for type providers

### ISSUE THREAD

**Issue by soc** [djspiewak/anti-xml#43]
It would make sense to work together with the Scala Integrated Query people to make sure Anti-XML can benefit from their work and provide fully typed XML via WSDL or schema files to users.

It would be very bad if we would need the third XML replacement in 2 years ...

Further information:

Type providers in F#: http://msdn.microsoft.com/en-us/library/hh156509%28v=VS.110%29.aspx with some blog post what people can do with it: http://tomasp.net/blog/goto-loosely-structured-data.aspx

http://stackoverflow.com/questions/7429999/are-there-plans-to-support-type-providers-for-scalas-siq-scalaintegratedquery/7431606#7431606

**Comment by djspiewak** [comment]
I think this is something we will revisit when the type provider stuff for SIQ reaches a greater level of maturity.  On a more philosophical level, I'm pretty strongly against type providers in general, so you may see me push back on this.  :-)

I'll leave this issue open to track the effort.

**Comment by soc** [comment]
Ok, thanks. I just hope Anti-XML will be able to integrate this functionality without too much breakage.

**Comment by mechanical-snail** [comment]
Daniel, what's your objection to type providers? I tried searching your name with "type providers" and I didn't find any rants ☺.
