### ISSUE TITLE
"console" command hangs in SBT

### ISSUE THREAD

**Issue by josharnold52** [djspiewak/anti-xml#46]
I think 2.9.1 broke something in the "initialCommands" functionality of SBT's console task.   When I enter "console", I see the initial commands followed by a scala> prompt and I can then enter a single line.   The REPL hangs after that.    The problem goes away if I switch back to 2.9.0-1 or if I remove the `initialCommands` setting from `build.sbt`

I'll log a related issue to SBT;  I'm guessing the issue is is in the interpreter itself, but I'm not familiar with how SBT interacts with it.

I did find one interpreter issue that might be related, but I haven't been able to get the suggested workaround to work in SBT:

https://issues.scala-lang.org/browse/SI-4945

**Comment by josharnold52** [comment]
The SBT Issue is at:

https://github.com/harrah/xsbt/issues/192

**Comment by josharnold52** [comment]
Oops.  It looks like this was fixed in 0.11   Closing...

https://github.com/harrah/xsbt/issues/175

**Comment by djspiewak** [comment]
Thanks for digging into this!  I thought I was going mad…  Hopefully SBT 0.11 will land soon.
