### ISSUE TITLE
Add Short-Circuit Deep-Select Operation on Selectable

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/anti-xml#48]
We need a version of deep-select that short circuits the tree traversal when it finds a match.  Thus, if there is a selector that matches some node as well as one or more of its children, the resulting `Group` will contain _only_ the parent node (rather than also containing the children).  The major advantage to such an operation would be guaranteed unambiguity in the `unselect` operation.  This short-circuit deep-select method should be named `\\!` (sound off in the comments if you have a better name!)

**Comment by josharnold52** [comment]
The `PathCreator` code in `zipper-replacement` looks pretty stable, so I'll start on this in the next couple of days unless someone else is already planning to.

**Comment by ncreep** [comment]
I do have intentions of doing a bit of cleaning up in `PathCreator`, but I don't it should be something too significant.

In any case, I won't be available to do anything until at least the end of the week.
So go ahead...

**Comment by josharnold52** [comment]
Pull request #65 adds this operator.
