### ISSUE TITLE
Deep-Select Should be a Depth-First Traversal

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/anti-xml#49]
Right now, deep-select is essentially equivalent to a `flatMap` recursive deep-select concatenated with the results of a shallow-select.  This is very convenient as a definition, but it's probably not the most intuitive ordering.  It's basically a breadth-first traversal, which is very different from the order in which you would encounter XML nodes in a lexical context.  This natural lexical ordering works out to be _depth_-first.  To mirror these (more intuitive) semantics, the deep-select operator should return items in a depth-first order.

**Comment by josharnold52** [comment]
The `PathCreator` code in `zipper-replacement` looks pretty stable, so I'll start on this in the next couple of days unless someone else is already planning to.

**Comment by ncreep** [comment]
I do have intentions of doing a bit of cleaning up in `PathCreator`, but I don't it should be something too significant.

In any case, I won't be available to do anything until at least the end of the week.
So go ahead...

**Comment by josharnold52** [comment]
Pull request #65 makes this change.
