### ISSUE TITLE
Performance of DeepZipper Selection Needs Significant Improvement

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/anti-xml#50]
Here are the latest `test-perf` results from my machine running on the zipper-replacement branch:

```
[info] -- System Information --
[info] Heap: 2039MB
[info] Java: Apple Inc. 1.6.0_26
[info] OS: Mac OS X 10.7.1 x86_64
[info] 
[info] -- Memory Usage (7 MB) --
[info] anti-xml:  53413432
[info] scala.xml: 26514864
[info] javax.xml: 49023256
[info] 
[info] -- Execution Time --
[info] Loading a 7 MB XML file
[info]  + anti-xml: min: 418 ms, max: 438 ms, average: 425 ms
[info]  + anti-xml StAX: min: 415 ms, max: 438 ms, average: 425 ms
[info]  + scala.xml: min: 241 ms, max: 255 ms, average: 248 ms
[info]  + javax.xml: min: 124 ms, max: 138 ms, average: 129 ms
[info] Shallow selection in a 7 MB tree
[info]  + anti-xml: min: 145618 ms, max: 148546 ms, average: 146193 ms
[info]  + scala.xml: min: 19 ms, max: 24 ms, average: 21 ms
[info] Deep selection in a 7 MB tree
[info]  + anti-xml: min: 1451 ms, max: 1518 ms, average: 1474 ms
[info]  + scala.xml: min: 270 ms, max: 285 ms, average: 277 ms
[info]  + javax.xml: min: 15 ms, max: 18 ms, average: 17 ms
```

Take special note of that shallow selection time!  Needless to say, we need to get that down a bit before we cut a release where selection is entirely based on DeepZipper.

**Comment by ncreep** [comment]
Do we have some predefined quick performance tests?
Something that runs within a minute, just to get a hint to whether an optimization has the desired effect.

**Comment by djspiewak** [comment]
The best performance test to run would be `test-perf shallowSelectSmall` (from the SBT shell).  Unfortunately, this test takes a _really_ long time right now because a single shallow select operation on a 7 MB tree requires two and a half minutes (and the test is run about a dozen times).  So, that's a little long.  However, if the performance were better, the test would complete quite quickly (on the master branch, I believe it only takes a few seconds).

**Comment by ncreep** [comment]
Blind optimizations FTW!

**Comment by djspiewak** [comment]
I'm _terribly_ sorry!  :-)  It would be pretty easy to just whip up a new performance test with a smaller tree, something that runs a little more quickly.  Alternatively, the performance is so dramatically slow right now that you can probably just check timing in the REPL and see differences.

**Comment by josharnold52** [comment]
Of course, there's always the tried and true method of "break into the debugger and see what's on the call stack".   When the performance is really out of whack, chances are you will break into the bottleneck :-)

**Comment by djspiewak** [comment]
With the very latest changes from ncreep, the performance is good enough that I wouldn't consider it a blocker any longer.  It could still stand some improvement, but I would feel comfortable cutting a release without further improvement.

**Comment by djspiewak** [comment]
With the latest changes from ncreep, I think we can consider this closed!
