### ISSUE TITLE
Elem hash code caching

### ISSUE THREAD

**Issue by ncreep** [djspiewak/anti-xml#55]
At the moment, unselection on`DeepZipper` relies on hashing of parent nodes lists, this eventually boils down to computing the hash code of the entire XML tree, which gets really slow when dealing with large trees.

One workaround for this would be to compute the hash using the locations of the parent nodes and ignoring the contents, similar to what I've done in the `Path` class in 93f92cfd3d521a4c28ed50e35ab9c96da158f23a.

A more elegant solution, to both problems,  is to cache the hash code of `Elem` instances upon creation. e.g. adding something like: `override val hashCode: Int = scala.runtime.ScalaRunTime._hashCode(this)` to `Elem` (not sure whether this should be transient or not).

Are there any problems to do so?

**Comment by djspiewak** [comment]
Sounds like a perfectly reasonable solution.  I'll implement now.
