### ISSUE TITLE
Zipper NodeMergeStrategy Should Be Parameter on unselect

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/anti-xml#62]
Right now, the `NodeMergeStrategy` is a member of `DeepZipper`.  This really should be an implicit parameter on `unselect` with the default instance (as defined in the companion object for `NodeMergeStrategy`) as `BasicNodeMergeStrategy`.  I think that's the default, anyway…

The only hang-up with just doing this straight away is that `NodeMergeStrategy` is a type alias for a function.  We can't take this as an implicit parameter, since it pollutes the implicit dispatch space.  Given that it is a function of arity-2, I don't _think_ it will be a problem, but I'd rather not take chances.  In any case, we need a companion object in order to handle lookup properly, and type aliases don't have that.

We need to redefine `NodeMergeStrategy` as a trait with an `apply` method.  Basically, isomorphic to the function it represents, but without _actually_ being a nominal function type.  Then, we can define the appropriate companion object and stick `BasicNodeMergeStrategy` into there.  We then add an implicit parameter to `unselect`, pass the data down the call chain and we're golden!

I'll take care of this in a few days if no one else gets to it first.  I think this is really the only thing remaining to be done before we land zipper-replacement in master.  (well, that and a rename of `DeepZipper` to `Zipper`, but that's trivial)

**Comment by josharnold52** [comment]
Note that pull request #63 makes this change, although it contains much more than that.
