### ISSUE TITLE
anti-xml_2.8.2-0.2

### ISSUE THREAD

**Issue by rossabaker** [djspiewak/anti-xml#68]
Any chance of a retro-release of 0.2 for Scala 2.8.2?  Specs is already published.  Still need a 2.8.2 ScalaCheck to do it The Right Way™.

**Comment by djspiewak** [comment]
Done!  Sorry for the delay, was a bit busy for a while there.  I wish I could do a 2.8.2 cross-build for 0.3, since it has so many new features and improvements, but it's just way too hard to keep up that compatibility when extending the collections framework.  :-(
