### ISSUE TITLE
Zipper issue replacing nested element with ancestor element of same name

### ISSUE THREAD

**Issue by rossajmcd** [djspiewak/anti-xml#83]
Hi. I am using antixml 0.3. I am having trouble with modifying the tree using Zippers.

Here is a gist for a successful experiment:

https://gist.github.com/1871638

And a failed experiment where things go awry and the replacement is erroneous:

https://gist.github.com/1871648

Note, in the failed experiment the original xml was modified so the 'replace' element with an id of 'bar' has an ancestor 'replace' element.

It could just be me, but I could not find a mailing list to dig deeper.

Thanks for your help.

**Comment by ncreep** [comment]
Hi.

Although somewhat counter intuitive, the `filter` function actually removes the failing nodes from the `Zipper`.
So the first `replace` and its children are completely removed upon unselection.

As far as I can see, you have two options:
- Use the `select` method with a custom `Selector`, this would look something like:

``` scala
val replace = original \\ 'replace select Selector {case item: Elem if item.attrs("id").contains("bar") => item }
replace.updated(0, insert).unselect.unselect
```

Note the second `unselect` is necessary as two selections are performed.
- Use a non default merging strategy to resolve the issue, i.e.:

``` scala
import com.codecommit.antixml.ZipperMergeStrategy._

val replace = (original \\ 'replace) filter (item => item.attrs("id").contains("bar"))
replace.updated(0, insert).unselect(AlwaysPreferChildren)
```

Although it works, this solution requires you to know beforehand something about the structure of the tree, so it's not as flexible as the `select` approach.

The user group is located [here](http://groups.google.com/group/anti-xml-users).

**Comment by rossajmcd** [comment]
Hi.

Awesome, thanks for the fast turnaround.  Your explanation and help both appreciated.

It's probably worth referencing the user group somewhere obvious on the site.

Thanks.
